version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/reddit_crawler_db
      - MYSQL_USERNAME=reddit_user
      - MYSQL_PASSWORD=reddit_password
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - VITE_TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
    depends_on:
      db:
        condition: service_healthy  # Wait for db to be healthy

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=reddit_crawler_db
      - MYSQL_USER=reddit_user
      - MYSQL_PASSWORD=reddit_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data: